name: Docker Build and Publish

on:
  schedule:
    - cron: '0 0 * * *'     # auto compile daily
  push:
    branches: [main]
    paths:
      - Dockerfile
      - .dockerignore
  pull_request:
    branches: [main]
    paths:
      - Dockerfile
      - .dockerignore
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1

jobs:
  metadata:
    name: Get image and repo details
    runs-on: ubuntu-latest

    outputs:
      name: ${{ steps.name.outputs.name }}
      tags: ${{ steps.metadata.outputs.tags }}
      labels: ${{ steps.metadata.outputs.labels }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate docker-compliant image name
        id: name
        run: echo "name=$(echo ${GITHUB_REPOSITORY,,} | sed 's/docker-//')" | tee -a $GITHUB_OUTPUT

      - name: Generate Docker metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: |
            docker.io/${{ steps.name.outputs.name }}
            ghcr.io/${{ steps.name.outputs.name }}
          tags: |
            type=raw,value=latest

  build_and_publish:
    name: Build and Publish Container Image
    runs-on: ubuntu-latest
    needs: metadata

    permissions:
      id-token: write
      packages: write
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ needs.metadata.outputs.tags }}
          labels: ${{ needs.metadata.outputs.labels }}
          platforms: linux/amd64
